/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dish/[id]': RouteRecordInfo<
      '/dish/[id]',
      '/dish/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/list/': RouteRecordInfo<
      '/list/',
      '/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/products/': RouteRecordInfo<
      '/settings/products/',
      '/settings/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/products/[id]': RouteRecordInfo<
      '/settings/products/[id]',
      '/settings/products/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/products/new': RouteRecordInfo<
      '/settings/products/new',
      '/settings/products/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/dish/[id].vue': {
      routes:
        | '/dish/[id]'
      views:
        | never
    }
    'src/pages/list/index.vue': {
      routes:
        | '/list/'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/products/index.vue': {
      routes:
        | '/settings/products/'
      views:
        | never
    }
    'src/pages/settings/products/[id].vue': {
      routes:
        | '/settings/products/[id]'
      views:
        | never
    }
    'src/pages/settings/products/new.vue': {
      routes:
        | '/settings/products/new'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
